-- 코드를 입력하세요
SELECT MEMBER_ID,MEMBER_NAME,GENDER,DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
from MEMBER_PROFILE 
WHERE MONTH(DATE_OF_BIRTH) = 3 and TLNO  IS NOT NULL and GENDER ='W'
order by MEMBER_ID asc;